database:
  type: "mysql"  # mysql, postgres, sqlite, sqlserver
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "mydb"
  ssl_mode: "disable"  # for postgres
  file: "database.db"  # for sqlite 